### ISSUE TITLE
Linearizable results and read-committed isolation

### ISSUE THREAD

**Issue by teads1** [jepsen-io/jepsen#392] opened 2019-05-29 21:58 UTC
I'm getting intermittent failures in the linearizable checker in my testing and I wanted to make sure I understand what the results are showing me.

![image](https://user-images.githubusercontent.com/5169332/58593576-1d152480-8220-11e9-9724-adaa748d667b.png)

In this case, p3 invokes a write 4.  P5 reads value of 3 (before p3 commits value of 4).  P8 starts a read, p5 commits value of 4 and p8 reads value of 4.

In the history, we see:

**{:type :invoke, :f :write, :value 4, :process 3, :time 33227098364, :index 430}**
{:type :invoke, :f :cas, :value [4 4], :process 4, :time 33227086620, :index 431}
**{:type :invoke, :f :cas, :value [0 1], :process 0, :time 33227072155, :index 432}**
{:type :invoke, :f :read, :value nil, :process 6, :time 33227118251, :index 433}
{:type :invoke, :f :read, :value nil, :process 9, :time 33227072155, :index 434}
{:type :invoke, :f :read, :value nil, :process 8, :time 33227118450, :index 435}
{:type :invoke, :f :cas, :value [0 4], :process 1, :time 33227112898, :index 436}
**{:type :invoke, :f :read, :value nil, :process 5, :time 33227135833, :index 437}**
{:type :invoke, :f :cas, :value [4 1], :process 2, :time 33227149972, :index 438}
{:type :ok, :f :read, :value 3, :process 6, :time 33601208721, :index 439}
**{:type :ok, :f :read, :value 3, :process 5, :time 33603040328, :index 440}**
{:type :ok, :f :read, :value 3, :process 8, :time 33603054540, :index 441}
{:type :ok, :f :read, :value 3, :process 9, :time 33603076992, :index 442}
**{:type :invoke, :f :read, :value nil, :process 8, :time 33723214082, :index 443}**
**{:type :ok, :f :cas, :value [0 1], :process 0, :time 33726300256, :index 444}**
{:type :invoke, :f :read, :value nil, :process 5, :time 33726840168, :index 445}
{:type :invoke, :f :read, :value nil, :process 7, :time 33726834790, :index 446}
{:type :fail, :f :cas, :value [4 1], :process 2, :time 33774882023, :index 447}
{:type :fail, :f :cas, :value [4 4], :process 4, :time 33774890220, :index 448}
{:type :fail, :f :cas, :value [0 4], :process 1, :time 33850528626, :index 449}
**{:type :ok, :f :write, :value 4, :process 3, :time 33947578008, :index 450}**
**{:type :ok, :f :read, :value 4, :process 8, :time 34092526731, :index 451}**

For a system with repeatable-read isolation, we would expect p8 to read value of 3 since it's snapshot started before p3 committed value of 4.  

```
{:op {:process 8,
         :type :invoke,
         :f :read,
         :value 4,
         :index 443,
         :time 33723214082},
         :model #knossos.model.Inconsistent{:msg "can't read 4 from register 3"}}
```

But for read-committed, p8 should read a value of 4 (read latest committed value).  In the distributed system I am testing with read-committed, this is an expected result (p8 reads value of 4).

Assuming I'm understanding these results correctly, is there an existing Knossos model better suited toward validating linearizability in read-committed isolation that I should be using?

**Comment by aphyr** [comment] 2019-05-29 22:41
Hmmm... Are you sure P8 is the problem here? Looks to me like the issue is the CAS op by process 0. See where all the lines turn pink leading into that op?--KyleOn May 29, 2019 17:58, Tim Eads <notifications@github.com> wrote:I'm getting intermittent failures in the linearizable checker in my testing and I wanted to make sure I understand what the results are showing me.

In this case, p3 invokes a write 4.  P5 reads value of 3 (before p3 commits value of 4).  P8 starts a read, p5 commits value of 4 and p8 reads value of 4.
In the history, we see:
{:type :invoke, :f :write, :value 4, :process 3, :time 33227098364, :index 430}
{:type :invoke, :f :cas, :value [4 4], :process 4, :time 33227086620, :index 431}
{:type :invoke, :f :cas, :value [0 1], :process 0, :time 33227072155, :index 432}
{:type :invoke, :f :read, :value nil, :process 6, :time 33227118251, :index 433}
{:type :invoke, :f :read, :value nil, :process 9, :time 33227072155, :index 434}
{:type :invoke, :f :read, :value nil, :process 8, :time 33227118450, :index 435}
{:type :invoke, :f :cas, :value [0 4], :process 1, :time 33227112898, :index 436}
{:type :invoke, :f :read, :value nil, :process 5, :time 33227135833, :index 437}
{:type :invoke, :f :cas, :value [4 1], :process 2, :time 33227149972, :index 438}
{:type :ok, :f :read, :value 3, :process 6, :time 33601208721, :index 439}
{:type :ok, :f :read, :value 3, :process 5, :time 33603040328, :index 440}
{:type :ok, :f :read, :value 3, :process 8, :time 33603054540, :index 441}
{:type :ok, :f :read, :value 3, :process 9, :time 33603076992, :index 442}
{:type :invoke, :f :read, :value nil, :process 8, :time 33723214082, :index 443}
{:type :ok, :f :cas, :value [0 1], :process 0, :time 33726300256, :index 444}
{:type :invoke, :f :read, :value nil, :process 5, :time 33726840168, :index 445}
{:type :invoke, :f :read, :value nil, :process 7, :time 33726834790, :index 446}
{:type :fail, :f :cas, :value [4 1], :process 2, :time 33774882023, :index 447}
{:type :fail, :f :cas, :value [4 4], :process 4, :time 33774890220, :index 448}
{:type :fail, :f :cas, :value [0 4], :process 1, :time 33850528626, :index 449}
{:type :ok, :f :write, :value 4, :process 3, :time 33947578008, :index 450}
{:type :ok, :f :read, :value 4, :process 8, :time 34092526731, :index 451}
For a system with repeatable-read isolation, we would expect p8 to read value of 3 since it's snapshot started before p3 committed value of 4.
{:op {:process 8,
         :type :invoke,
         :f :read,
         :value 4,
         :index 443,
         :time 33723214082},
         :model #knossos.model.Inconsistent{:msg "can't read 4 from register 3"}}

But for read-committed, p8 should read a value of 4 (read latest committed value).  In the distributed system I am testing with read-committed, this is an expected result (p8 reads value of 4).
Assuming I'm understanding these results correctly, is there an existing Knossos model better suited toward validating linearizability in read-committed isolation that I should be using?

**Comment by teads1** [comment] 2019-05-30 19:20
I guess I'm not understanding how the CAS [0 1] for p0 leads to an inconsistent state.  If I'm reading this right, CAS compares its first value (0) to current value in register (3, eventually 4) - if they match, CAS op updates register to its second value (1).  Whether the current register is 3 or 4, the CAS won't change register value because the current value isn't 0, right?  Why would knossos consider either of these "inconsistent"?

```
[{:op {:process 5,
   :type :ok,
   :f :read,
   :value 3,
   :index 440,
   :time 33603040328},
   :model #knossos.model.CASRegister{:value 3}}
  {:op {:process 3,
   :type :invoke,
   :f :write,
   :value 4,
   :index 430,
   :time 33227098364},
   :model #knossos.model.CASRegister{:value 4}}
  {:op {:process 8,
    :type :invoke,
    :f :read,
    :value 4,
    :index 443,
    :time 33723214082},
    :model #knossos.model.CASRegister{:value 4}}
   {:op {:process 0,
    :type :ok,
    :f :cas,
    :value [0
                 1],
    :index 444,
    :time 33726300256},
    :model #knossos.model.Inconsistent{:msg "can't CAS 4 from 0 to 1"}}]
 [{:op {:process 5,
    :type :ok,
    :f :read,
    :value 3,
    :index 440,
    :time 33603040328},
    :model #knossos.model.CASRegister{:value 3}}
   {:op {:process 0,
     :type :ok,
     :f :cas,
     :value [0
                  1],
     :index 444,
     :time 33726300256},
     :model #knossos.model.Inconsistent{:msg "can't CAS 3 from 0 to 1"}}]
```

![image](https://user-images.githubusercontent.com/5169332/58654613-290af000-82cd-11e9-86e4-ca4f8fa5161f.png)

**Comment by aphyr** [comment] 2019-05-30 19:29
The fact that the CAS op succeeded means that at some point during P0's invocation of (cas [0 1]), the value must have been one. The diagram is telling you that the available values during this time were either 4 or 3, and neither of those is 0.

**Comment by teads1** [comment] 2019-05-30 21:10
Indeed...

**{:type :invoke, :f :write, :value [1 0], :process 3, :time 32227919892, :index 409}**
{:type :invoke, :f :write, :value [1 3], :process 0, :time 32227913728, :index 410}
{:type :invoke, :f :cas, :value [1 [0 3]], :process 2, :time 32227942124, :index 411}
{:type :invoke, :f :read, :value [1 nil], :process 5, :time 32227915528, :index 412}
{:type :invoke, :f :read, :value [1 nil], :process 9, :time 32227922087, :index 413}
{:type :invoke, :f :cas, :value [1 [0 0]], :process 4, :time 32227958348, :index 414}
{:type :invoke, :f :read, :value [1 nil], :process 7, :time 32227973506, :index 415}
{:type :ok, :f :read, :value [1 nil], :process 8, :time 32598420780, :index 416}
{:type :ok, :f :read, :value [1 nil], :process 5, :time 32602853272, :index 417}
{:type :ok, :f :read, :value [1 nil], :process 7, :time 32605663478, :index 418}
{:type :ok, :f :read, :value [1 nil], :process 6, :time 32605663350, :index 419}
{:type :ok, :f :read, :value [1 nil], :process 9, :time 32606373513, :index 420}
{:type :invoke, :f :read, :value [1 nil], :process 8, :time 32725981613, :index 421}
{:type :invoke, :f :read, :value [1 nil], :process 7, :time 32727702211, :index 422}
{:type :ok, :f :write, :value [1 3], :process 0, :time 32733673239, :index 423}
{:type :fail, :f :cas, :value [1 [4 0]], :process 1, :time 32778093240, :index 424}
{:type :fail, :f :cas, :value [1 [0 0]], :process 4, :time 32781130339, :index 425}
{:type :fail, :f :cas, :value [1 [0 3]], :process 2, :time 32781166987, :index 426}
**{:type :ok, :f :write, :value [1 0], :process 3, :time 32932034443, :index 427}**
{:type :ok, :f :read, :value [1 3], :process 8, :time 33098402713, :index 428}
{:type :ok, :f :read, :value [1 3], :process 7, :time 33103965115, :index 429}
{:type :invoke, :f :write, :value [1 4], :process 3, :time 33227098364, :index 430}
{:type :invoke, :f :cas, :value [1 [4 4]], :process 4, :time 33227086620, :index 431}
**{:type :invoke, :f :cas, :value [1 [0 1]], :process 0, :time 33227072155, :index 432}**
{:type :invoke, :f :read, :value [1 nil], :process 6, :time 33227118251, :index 433}
{:type :invoke, :f :read, :value [1 nil], :process 9, :time 33227072155, :index 434}
{:type :invoke, :f :read, :value [1 nil], :process 8, :time 33227118450, :index 435}
{:type :invoke, :f :cas, :value [1 [0 4]], :process 1, :time 33227112898, :index 436}
{:type :invoke, :f :read, :value [1 nil], :process 5, :time 33227135833, :index 437}
{:type :invoke, :f :cas, :value [1 [4 1]], :process 2, :time 33227149972, :index 438}
{:type :ok, :f :read, :value [1 3], :process 6, :time 33601208721, :index 439}
{:type :ok, :f :read, :value [1 3], :process 5, :time 33603040328, :index 440}
{:type :ok, :f :read, :value [1 3], :process 8, :time 33603054540, :index 441}
{:type :ok, :f :read, :value [1 3], :process 9, :time 33603076992, :index 442}
{:type :invoke, :f :read, :value [1 nil], :process 8, :time 33723214082, :index 443}
**{:type :ok, :f :cas, :value [1 [0 1]], :process 0, :time 33726300256, :index 444}**

So, I've got a stale read with the process0 CAS...

**Comment by aphyr** [comment] 2019-05-30 21:19
Yeah, that could be a stale read. Which is legal, under read-committed! RC doesn't say anything about time order; you're allowed to read arbitary values from the past or future. If your system is RC and *not* linearizable, you may not want to use a linearizability checker on it. :)

**Comment by aphyr** [comment] 2019-10-19 13:27
Gonna go ahead and close this, unless you have further questions. :)

**Closed by aphyr** 2019-10-19 13:27 UTC
